apiVersion: v1
kind: Service
metadata:
  name: {{ include "excalidraw.fullname" . }}-frontend
  labels: {{- include "excalidraw.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "excalidraw.name" . }}
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
