# Reminder: Main task is to make Excalidraw suitable for K8s deployment with Helm charts
{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "excalidraw.fullname" . }}
  labels:
    {{- include "excalidraw.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "excalidraw.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
{{- end }}