# Reminder: Main task is to make Excalidraw suitable for K8s deployment with Helm charts
apiVersion: v1
kind: Service
metadata:
  name: {{ include "excalidraw.fullname" . }}
  labels:
    {{- include "excalidraw.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "excalidraw.selectorLabels" . | nindent 4 }}