# Reminder: Main task is to make Excalidraw suitable for K8s deployment with Helm charts
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: excalidraw
  namespace: excalidraw
  labels:
    app.kubernetes.io/name: excalidraw
    app.kubernetes.io/instance: excalidraw
    app.kubernetes.io/component: pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: excalidraw
      app.kubernetes.io/instance: excalidraw