# Reminder: Main task is to make Excalidraw suitable for K8s deployment with Helm charts
apiVersion: v1
kind: ServiceAccount
metadata:
  name: excalidraw
  namespace: excalidraw
  labels:
    app.kubernetes.io/name: excalidraw
    app.kubernetes.io/instance: excalidraw
    app.kubernetes.io/component: serviceaccount